### ISSUE TITLE
Build Failed with Xcode 7.0.1 error on AppDelegate.m

### ISSUE THREAD

**Issue by didysinchan** [floatinghotpot/cordova-admob-pro#248]
Hello friends, here I have some error on your plugin when I want to archive to submit on AppStore.

Error message:
ld: bitcode bundle could not be generated because '/Users/didyseptiyono/Desktop/test1/platforms/ios/Test1/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Here is my screenshoot
![image](https://cloud.githubusercontent.com/assets/9065898/10869959/38a0ddd6-80f1-11e5-9e25-e1a9d709768a.png)

Do you have ad advice for this error?

**Comment by floatinghotpot** [comment]
thanks for the bug report, it has been fixed just now. 

please update the plugins to:
```
cordova-plugin-admobpro, v2.9.9
cordova-plugin-extension, v1.2.2
```

**Comment by floatinghotpot** [comment]
BTW, when you archive, if you see some error like,
```‘Cordova/CDVViewController.h’ file not found```

Please check the discussion and solution here:
http://forum.ionicframework.com/t/cordova-cdvviewcontroller-h-file-not-found-in-xcode-7-1-beta/32232/14

FYI.

**Comment by didysinchan** [comment]
Thanks raymond for help, you save my day.

**Comment by ivanthecrazy** [comment]
@floatinghotpot 
```
cordova-plugin-admobpro, v2.9.9
cordova-plugin-extension, v1.2.2
```
This doesn't solve the issue. I'm getting the same error during project archiving for AdHoc distribution.

**Comment by floatinghotpot** [comment]
Could you please paste the new screenshot with error logs?

**Comment by stechavat** [comment]
Raymond, could you please update the cordova-plugin-admob-iad mediation plugin to solve the bitcode issue?

**Comment by ivanthecrazy** [comment]
@floatinghotpot 
![2015-11-05 13-49-45 scratchitup xcodeproj](https://cloud.githubusercontent.com/assets/736384/10965105/3aadb524-83c4-11e5-8086-b868b09d7748.png)

```
MacBook-Pro-Ivan:ScratchItUp IvanTheCrazy$ cordova plugin ls
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-admobpro 2.9.9 "AdMob Plugin Pro"
cordova-plugin-camera 1.2.0 "Camera"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-crosswalk-webview 1.3.1 "Crosswalk WebView Engine"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-extension 1.2.2 "Cordova Plugin Extension"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-file-transfer 1.3.0 "File Transfer"
cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-x-socialsharing 5.0.6 "SocialSharing"
phonegap-plugin-push 1.4.2 "PushPlugin"
```

**Comment by obeone** [comment]
Hi,

Same problem here when building using command line : 
```
ld: 'Ze-Coloc/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADGestureIdUtil.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm using cordova-plugin-admobpro v2.9.9

**Comment by l1nknyto** [comment]
Hi Raymond,

I'm experience same problem here.
I'm currently using:
- cordova-plugin-admobpro 2.12.0 "AdMob Plugin Pro"
- cordova-plugin-extension 1.2.9 "Cordova Plugin Extension"

Do you have ad advice for this error?
Thanks for your help

**Comment by gemanor** [comment]
As @l1nknyto said the error is back in latest versions...

**Comment by floatinghotpot** [comment]
Can you paste the error logs?

**Comment by floatinghotpot** [comment]
it's just fixed a few hours ago, please update the plugin and try again.

**Comment by gemanor** [comment]
I'll update, thanks!
To help who had this problem and can't update plugin, you can set 'Enable bitcode' to off at build settings page, it will fix it

**Comment by floatinghotpot** [comment]
Reminder:
If you use Cordova CLI to build, by default, it's bitcode OFF. 
If you open in XCode, by default, it's enable bitcode ON.

Anyway, the new plugin should work no matter bitcode ON or OFF.

**Comment by gemanor** [comment]
The error still appear when bitcode is enabled

`Ld /Users/gmanor/Library/Developer/Xcode/DerivedData/Spor-gnerrmkiasnxflccjoqxpzclqqrd/Build/Intermediates/ArchiveIntermediates/Spor/IntermediateBuildFilesPath/Spor.build/Release-iphoneos/Spor.build/Objects-normal/arm64/Spor normal arm64
    cd /Users/gmanor/Development/spor/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -L/Users/gmanor/Library/Developer/Xcode/DerivedData/Spor-gnerrmkiasnxflccjoqxpzclqqrd/Build/Intermediates/ArchiveIntermediates/Spor/BuildProductsPath/Release-iphoneos -L/Users/gmanor/Development/spor/platforms/ios/Spor/Plugins/cordova-plugin-google-analytics -L/Users/gmanor/Development/spor/platforms/ios/Spor/Plugins/cordova-plugin-extension -F/Users/gmanor/Library/Developer/Xcode/DerivedData/Spor-gnerrmkiasnxflccjoqxpzclqqrd/Build/Intermediates/ArchiveIntermediates/Spor/BuildProductsPath/Release-iphoneos -FSpor/Plugins/cordova-plugin-admobpro -filelist /Users/gmanor/Library/Developer/Xcode/DerivedData/Spor-gnerrmkiasnxflccjoqxpzclqqrd/Build/Intermediates/ArchiveIntermediates/Spor/IntermediateBuildFilesPath/Spor.build/Release-iphoneos/Spor.build/Objects-normal/arm64/Spor.LinkFileList -miphoneos-version-min=8.0 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/gmanor/Library/Developer/Xcode/DerivedData/Spor-gnerrmkiasnxflccjoqxpzclqqrd/Build/Intermediates/ArchiveIntermediates/Spor/BuildProductsPath/Release-iphoneos -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/gmanor/Library/Developer/Xcode/DerivedData/Spor-gnerrmkiasnxflccjoqxpzclqqrd/Build/Intermediates/ArchiveIntermediates/Spor/BuildProductsPath/Release-iphoneos/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework CFNetwork -framework SystemConfiguration -lGoogleAnalyticsServices -framework CoreData -lz -lsqlite3 -weak_framework Social -lCordovaGenericAd -framework GoogleMobileAds -framework AdSupport -framework AudioToolbox -framework AVFoundation -framework CoreLocation -framework CoreTelephony -framework EventKit -framework EventKitUI -framework Foundation -framework MediaPlayer -framework MessageUI -framework QuartzCore -framework StoreKit -framework UIKit -Xlinker -dependency_info -Xlinker /Users/gmanor/Library/Developer/Xcode/DerivedData/Spor-gnerrmkiasnxflccjoqxpzclqqrd/Build/Intermediates/ArchiveIntermediates/Spor/IntermediateBuildFilesPath/Spor.build/Release-iphoneos/Spor.build/Objects-normal/arm64/Spor_dependency_info.dat -o /Users/gmanor/Library/Developer/Xcode/DerivedData/Spor-gnerrmkiasnxflccjoqxpzclqqrd/Build/Intermediates/ArchiveIntermediates/Spor/IntermediateBuildFilesPath/Spor.build/Release-iphoneos/Spor.build/Objects-normal/arm64/Spor

ld: object contains invalid bitcode: /Users/gmanor/Development/spor/platforms/ios/Spor/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by floatinghotpot** [comment]
Weird. I've verified it with bitcode ON. 

Try creating a new cordova project, and check the plugin version as following?

cordova-plugin-admobpro@2.15.0
cordova-plugin-extension@1.4.2

**Comment by gemanor** [comment]
I verified that my version is 2.15.0 & 1.4.2
I will add new project later
Thanks
