### ISSUE TITLE
Android device back button closes app after loading ad banner

### ISSUE THREAD

**Issue by drakanor** [floatinghotpot/cordova-admob-pro#256]
After the first banner has been successfully loaded, the native back button of Android devices is not working as intended anymore. It closes/hides the Cordova app immediately instead of going backwards in history. Before loading the banner (even if the plugin is present) everything works as expected.

We tested this with Cordova 4.0.2 on Android 5.1.1 and 4.4.2 on smartphones and tablets: same behaviour on all devices.

**Comment by webextremeconcept** [comment]
Having same problem too. Is it due to the recent update? Is there an older version of admob that we can use? My backbutton no longer works. I am using phonegap build. Hence, I don't have the option of editing cordova webview.

**Comment by CiroXM** [comment]
I have the same problem. Cordova 5.4.1, Android 5.0.1.

**Comment by floatinghotpot** [comment]
The root cause is, when banner is displayed, the focus is on the banner webview instead of cordova main webview. when back button pressed, the banner webview will make the app quit. 

It's fixed now, by requesting focus on main webview after banner showed.

**Comment by Titoine** [comment]
Hi,
there is **still the problem** when a **banner is show** and after that you **show an interstitial**.
When you **close the interstitial** the **focus is back again on the banner** and when back button pressed, the banner webview will make the app quit.

Anyway, thanks for the great plugin !

**Comment by floatinghotpot** [comment]
Thanks for the bug report, I will verify and fix it if it's reproducible.

**Comment by arcadoo** [comment]
Yep... the same problem here... How can we change the focus on app webView after we close the interstitial Ad?

**Comment by arcadoo** [comment]
I saw that but still have the same problem as Titoine. After close the interstitial ad i think the webview return to banner so when i press back button it will force shutdown the app...! 

Thnaks a lot!

**Comment by Titoine** [comment]
Still have the issue even with the update.
Android 6.0 Galaxy s6

**Comment by arcadoo** [comment]
Ok, the solution is here:

In CordovaActivity.java(which is in platforms\android\CordovaLib\src\org\apache\cordova), add this method:

    @Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        if (this.appView != null) {

            View webview = this.appView.getView();
            if (webview != null) {
                return webview.dispatchKeyEvent(event);
            }

            return true;
        }

        return false;
    }

I found it from here:https://github.com/floatinghotpot/cordova-admob-pro/issues/161

**Comment by floatinghotpot** [comment]
Yes, you are correct. You can manually modify the Cordova framework code to fix it. 

Maybe, we should send a PR to Cordova framework team, or else you will have to modify it for every cordova CLI generated project.

**Comment by arcadoo** [comment]
Do you have any idea if that issue happen to the other platform too???? (IOS and Windows mobile)

**Comment by floatinghotpot** [comment]
There is no 'backbutton' on iOS device, so you don't have to worry about this.
