### ISSUE TITLE
Whole view is refreshed when ad is received (event onAdLoaded is fired)

### ISSUE THREAD

**Issue by neslinesli93** [floatinghotpot/cordova-admob-pro#280]
The main view flickers when an ad is received for the first time. It should not be like that because there is no need to refresh the whole view!
I am using a fresh clone of [ionic-m-generator] (https://github.com/mwaylabs/generator-m-ionic), and I'm running the test on a Samsung Galaxy S4 with Android Lollipop 5.0.1.
Please help with this issue, the experience is pretty bad at this point and there are no real alternatives to admob/fb SDKs on Cordova.

**Comment by floatinghotpot** [comment]
Thanks for the bug report. Will look into it.

**Comment by neslinesli93** [comment]
I don't know much of Android/Cordova development, but maybe the problem is that the ad is bound to the main view. On pretty much every ad integration guide, including the one made by Google, each ad has an unique ID defined in layout.xml and that ID is used for updating the view with the actual ad (see [here] (https://github.com/googleads/googleads-mobile-android-examples/blob/master/admob/BannerExample/app/src/main/java/com/google/android/gms/example/bannerexample/MyActivity.java#L40)).
So the affected code should be [this] (https://github.com/floatinghotpot/cordova-admob-pro/blob/master/src/android/AdMobPlugin.java#L107) and [this too](https://github.com/floatinghotpot/cordova-admob-pro/blob/master/src/android/AdMobPlugin.java#L121).
Furthermore, some interesting stuff seems to happen in cordova-plugin-extension, but unfortunately there is only a .jar file provided with no source :(

**Comment by marcusds** [comment]
I am also running into this issue. It would be nice to see it resolved.

**Comment by neslinesli93** [comment]
This plugin is completely broken (on Android at least).
There are multiple github issues, forum posts on ionic, etc and the conclusion is that you should avoid using this plugin if you care about your users and what you are trying to build.
In fact I am using Audience Networks that have Javascript SDK, like InMobi and MobFox: these companies' TOS does not forbid the usage of their Javascript SDK inside hybrid apps!

**Comment by kevinleequinn** [comment]
got everything working and just bought a license - this flicker is my only issue.

I am seeing it on all Android devices Jellybean through Marshmallow.

happens on orientation change as well if orientationRenew is true.

**Comment by eleva** [comment]
Hello, I'm running into this issue too.
I have an app with Ionic and the view refresh every time i show/hide the banner (configured with DFP).
Did you find a solution?

**Comment by floatinghotpot** [comment]
The code related with this issue has been refactored. I did not observe flickers every time in new version. Could you verify it in your test?

At first time the ad loaded, if set ```overlap:false```, the plugin will resize the webview, a flicker is not avoidable. If the banner is already visible, only ad content refresh won't cause app flicker.

Another method to avoid flicker is set ```overlap:true```, then plugin won't resize the webview, but you have to reserve a margin area at bottom, to avoid the banner overlap your webview content.

**Comment by floatinghotpot** [comment]
And, It's not recommended to call AdMob.showBanner() every time 'onAdLoaded' event is fired. As it will refresh the banner view and layout, which might cause flicker.

The best way to use banner, is to set ```autoShow:true```, and let it display when ad resource ready.

**Comment by marcusds** [comment]
I switched to this plugin: https://github.com/admob-google/admob-cordova

It manages to do this without the flicker.

**Comment by neslinesli93** [comment]
Thanks for the link @marcusds 
I would push cordova admobpro if it were open source: the repo called "cordova extension" contains the actual code that calls Google Play/Cocoa API, and at least for android it is closed source. The author commits only version changes along with a new jar every time!

**Comment by floatinghotpot** [comment]
The link given by @marcusds is not open source at all, only jar/lib. 
See: https://github.com/admob-google/admob-cordova/tree/master/src/android/libs

@neslinesli93 AdMobPro is partial open source, you will see part of the source code here:
https://github.com/floatinghotpot/cordova-admob-pro/tree/master/src/android

Here I explained why I will keep part of code closed: https://github.com/floatinghotpot/cordova-admob-pro/issues/242

If you want hack it yourself, here is my fully open source version, welcome to fork and DIY.
https://github.com/floatinghotpot/cordova-plugin-admob

**Comment by eleva** [comment]
@floatinghotpot Issue is fixed!
Thank you!
It does not filck even when ad is received!

I just have to remove plugin and then add it again.

For anyone using Ionic, I create the Banner with overlap:false and autoShow:false, then I show/hide it (giving showBanner function the position as parameter) in $ionicView.enter/$ionicView.leave events.

**Comment by kevinleequinn** [comment]
hi Raymond, can you push the latest up to npm?
I am using PhoneGap Build...

**Comment by floatinghotpot** [comment]
@kevinleequinn It's already published to npm, see: https://www.npmjs.com/package/cordova-plugin-admobpro

Please make sure following lines in your config.xml:
```xml
<preference name="android-build-tool" value="gradle" /> 
<gap:plugin name="cordova-plugin-admobpro" source="npm" />
```

See more details for PhoneGap Build:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/00.-How-To-Use-with-PhoneGap-Build

**Comment by neslinesli93** [comment]
@eleva could you please share your solution? I am still getting flickering even if I follow your instructions

**Comment by kevinleequinn** [comment]
yep Raymond, it's updated now.  thx!
